// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGS4-yZ7lelztj0_SmW8AMmhNeIdMhgMo',
    appId: '1:313912091901:web:69a22b994d878c1ca50a94',
    messagingSenderId: '313912091901',
    projectId: 'qrbuddy-28972',
    authDomain: 'qrbuddy-28972.firebaseapp.com',
    storageBucket: 'qrbuddy-28972.appspot.com',
    measurementId: 'G-0L563FZWK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrBJnVrnVeiGIyYRCDv8ZbGP8ymCkt5g',
    appId: '1:313912091901:android:c8408e9452ebfbf2a50a94',
    messagingSenderId: '313912091901',
    projectId: 'qrbuddy-28972',
    storageBucket: 'qrbuddy-28972.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBjfpfvk8Jd-dfJwTe4spcAxP5BfHWCVo',
    appId: '1:313912091901:ios:48996b28ef9d3db1a50a94',
    messagingSenderId: '313912091901',
    projectId: 'qrbuddy-28972',
    storageBucket: 'qrbuddy-28972.appspot.com',
    iosBundleId: 'com.nxtdesigns.qrbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBjfpfvk8Jd-dfJwTe4spcAxP5BfHWCVo',
    appId: '1:313912091901:ios:b2827dd402e98e3ea50a94',
    messagingSenderId: '313912091901',
    projectId: 'qrbuddy-28972',
    storageBucket: 'qrbuddy-28972.appspot.com',
    iosBundleId: 'com.example.qrBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQVMzU651s4HADUd46qAeHQDQVjmrF4LA',
    appId: '1:313912091901:web:a8f21f02454da99ca50a94',
    messagingSenderId: '313912091901',
    projectId: 'qrbuddy-28972',
    authDomain: 'qrbuddy-28972.firebaseapp.com',
    storageBucket: 'qrbuddy-28972.appspot.com',
    measurementId: 'G-Z46YW31QKQ',
  );
}
